### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by bxc237** [ethz-asl/time_autosync#2]
Hi @ZacharyTaylor, Kalibr tells me the timeshift of camera and IMU on my VI sensor is -0.36. How can I leverage your tool to tackle such large offset? Thank you.

**Comment by ZacharyTaylor** [comment]
This tool was designed for roughly estimating an unobserved offset online. If you have a better estimate from another source (such as Kalibr) you are probably best to just add this offset to the timestamps in your cameras ros driver.

**Comment by bxc237** [comment]
@ZacharyTaylor Ok, I see. How about cuckoo_time_translator? It just gives us more stable/accurate timestamps and it won't touch the offset, right?

**Comment by ZacharyTaylor** [comment]
Yes cuckoo_time_translator would be a good choice for this as it just helps to compensate for the random delays between a camera transmitting an image and your system receiving it

**Comment by bxc237** [comment]
Thank you!
